// <auto-generated />
namespace Cynfo1._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_greeting_message_to_areas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_greeting_message_to_areas));
        
        string IMigrationMetadata.Id
        {
            get { return "201704240000208_add_greeting_message_to_areas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
