// <auto-generated />
namespace Cynfo1._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addCompanyFieldToAds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCompanyFieldToAds));
        
        string IMigrationMetadata.Id
        {
            get { return "201702151615414_addCompanyFieldToAds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
